version: '3'

services:
  # MariaDB
  db:
    image: mariadb:10.6
    container_name: todo-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - todo-network

  # Node.js
  app:
    build:
      context: ./backend
    container_name: todo-node
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: todouser
      DB_PASSWORD: todopass
      DB_NAME: tododb
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mariadb_data: